# Copyright (c) 2018 Hunan ChenHan Information Technology Co., Ltd.
#
# SPDX-License-Identifier: GPL-3.0
#
# @author Ding Tao <miyatsu@qq.com>
#
# @date 3rd Dec, 2018
#
# @brief This Makefile is use apt to install openssh


all:
	./install.sh $(BUILD_DIR) $(OUTPUT_DIR)

