# Copyright (c) 2018 Hunan ChenHan Information Technology Co., Ltd.
#
# SPDX-License-Identifier: GPL-3.0
#
# @author Ding Tao <miyatsu@qq.com>
#
# @date 28th Nov, 2018
#
# @brief This Makefile is for reset program

all: hw_button

hw_button: main.c -lpthread
	gcc -o /usr/local/bin/hw_button main.c -lpthread

